name: csv-xlsx-app

services:
  converter:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8501:8501"
    command: >
      streamlit run app.py
      --server.address=0.0.0.0
      --server.port=8501
      --server.headless=true
      --server.fileWatcherType=none
      --browser.gatherUsageStats=false